{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 104,
   "metadata": {},
   "outputs": [],
   "source": [
    "from openai import OpenAI\n",
    "import os\n",
    "\n",
    "# client = OpenAI(base_url=\"https://api.groq.com/openai/v1\",\n",
    "#                 api_key=os.environ['GROQ_API_KEY'])\n",
    "client = OpenAI(base_url=\"https://api.groq.com/openai/v1\",\n",
    "                api_key='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')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 105,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "    You're Waaban, a virtual health assistant designed to provide personalized health and wellness guidance. you will help patient address their medical concerns and if need be help them connect with healthcare providers.\n",
      "    Generate a personalized response based on the following customer data and relevant category.\n",
      "\n",
      "    1. **General Information**:\n",
      "       - Name: None\n",
      "       - Age: 30\n",
      "       - Gender: male\n",
      "       - Location: None\n",
      "\n",
      "    2. **Health Information**:\n",
      "       - Symptoms: I have a rash on my penis\n",
      "       - Existing Conditions: None\n",
      "       - Current Medications: None\n",
      "       - Allergies: None\n",
      "       - Medical History: None\n",
      "       - Family History: None\n",
      "       - Surgery History: None\n",
      "\n",
      "    3. **Lifestyle Details**:\n",
      "       - Pregnancy Status: None\n",
      "       - Smoking Status: None\n",
      "       - Alcohol Consumption: None\n",
      "       - Exercise Frequency: None\n",
      "       - Sleep Duration: None\n",
      "       - Physical Activity: None\n",
      "       - Diet Preferences: None\n",
      "       - Vaccination Status: None\n",
      "\n",
      "    4. **Category Derived from Symptoms**:\n",
      "       - Relevant Category: General Wellness\n",
      "\n",
      "    Based on the provided data and category (General Wellness), generate a comprehensive and professional response that:\n",
      "    - Addresses the customer's concerns and symptoms.\n",
      "    - Offers personalized recommendations and guidance based on their unique situation.\n",
      "    - help them connect with local healthcare providers or resources if needed.\n",
      "    Ensure the response is empathetic, practical, and tailored to the customer's unique situation, while offering actionable steps and reminders to support their well-being.\n",
      "    \n"
     ]
    }
   ],
   "source": [
    "def determine_category(symptoms):\n",
    "    # Simple logic to categorize based on symptoms (you can expand this logic as needed)\n",
    "    symptoms_lower = symptoms.lower()\n",
    "    if any(keyword in symptoms_lower for keyword in [\"headache\", \"pain\", \"fever\", \"runny nose\", \"cough\", \"fatigue\"]):\n",
    "        return \"Physical Health and Wellness\"\n",
    "    elif any(keyword in symptoms_lower for keyword in [\"anxiety\", \"stress\", \"depression\", \"mood\", \"sleep\"]):\n",
    "        return \"Mental and Emotional Health\"\n",
    "    elif any(keyword in symptoms_lower for keyword in [\"sti\", \"sexual\", \"intimacy\", \"partner\", \"sexual health\"]):\n",
    "        return \"Sexual Health and Intimacy\"\n",
    "    else:\n",
    "        return \"General Wellness\"  # Default category if symptoms don't match specific criteria\n",
    "\n",
    "def generate_optimized_prompt(customer_data):\n",
    "    # Determine the category based on symptoms\n",
    "    category = determine_category(customer_data.get(\"symptoms\", \"\"))\n",
    "    \n",
    "    # Generate the prompt based on customer data and determined category\n",
    "    prompt = f\"\"\"\n",
    "    You're Waaban, a virtual health assistant designed to provide personalized health and wellness guidance. you will help patient address their medical concerns and if need be help them connect with healthcare providers.\n",
    "    Generate a personalized response based on the following customer data and relevant category.\n",
    "\n",
    "    1. **General Information**:\n",
    "       - Name: {customer_data.get('name')}\n",
    "       - Age: {customer_data.get('age')}\n",
    "       - Gender: {customer_data.get('gender')}\n",
    "       - Location: {customer_data.get('location')}\n",
    "\n",
    "    2. **Health Information**:\n",
    "       - Symptoms: {customer_data.get('symptoms')}\n",
    "       - Existing Conditions: {customer_data.get('conditions')}\n",
    "       - Current Medications: {customer_data.get('medications')}\n",
    "       - Allergies: {customer_data.get('allergies')}\n",
    "       - Medical History: {customer_data.get('medical_history')}\n",
    "       - Family History: {customer_data.get('family_history')}\n",
    "       - Surgery History: {customer_data.get('surgery_history')}\n",
    "\n",
    "    3. **Lifestyle Details**:\n",
    "       - Pregnancy Status: {customer_data.get('pregnancy_status')}\n",
    "       - Smoking Status: {customer_data.get('smoking_status')}\n",
    "       - Alcohol Consumption: {customer_data.get('alcohol_consumption')}\n",
    "       - Exercise Frequency: {customer_data.get('exercise_frequency')}\n",
    "       - Sleep Duration: {customer_data.get('sleep_duration')}\n",
    "       - Physical Activity: {customer_data.get('physical_activity')}\n",
    "       - Diet Preferences: {customer_data.get('diet_preferences')}\n",
    "       - Vaccination Status: {customer_data.get('vaccination_status')}\n",
    "\n",
    "    4. **Category Derived from Symptoms**:\n",
    "       - Relevant Category: {category}\n",
    "\n",
    "    Based on the provided data and category ({category}), generate a comprehensive and professional response that:\n",
    "    - Addresses the customer's concerns and symptoms.\n",
    "    - Offers personalized recommendations and guidance based on their unique situation.\n",
    "    - help them connect with local healthcare providers or resources if needed.\n",
    "    Ensure the response is empathetic, practical, and tailored to the customer's unique situation, while offering actionable steps and reminders to support their well-being.\n",
    "    \"\"\"\n",
    "    return prompt\n",
    "# user schema: name, purpose : conveinece, anytime help, instant response, central repo stats. health card info via message. \n",
    "# id, ticket, account, prediction while on call, doctor tickets created \n",
    "# Example usage\n",
    "customer_data = {\n",
    "    \"Name\": \"John Doe\",\n",
    "    \"symptoms\": \"I have a rash on my penis\",\n",
    "    \"age\": \"30\",\n",
    "    \"gender\": \"male\",\n",
    "    \"existing_conditions\": \"None\",\n",
    "    \"current_medications\": \"None\",\n",
    "    \"allergies\": \"None\"\n",
    "}\n",
    "\n",
    "\n",
    "# Generate prompt\n",
    "prompt = generate_optimized_prompt(customer_data)\n",
    "print(prompt)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 106,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'Subject': 'Health Guidance for Rupin Munjal', 'Response': \"Hi Rupin Munjal, I am Waaban, a virtual health assistant designed to provide personalized health and wellness guidance. Based on your provided information, here is my response:\\n    \\n    \\n        Provide a personalized set of recommendations to enhance the user's physical well-being. Address their symptoms: I feel nauseous and have a headache, I went to a strip club last night and had sex with a stripper. Include suggestions for dietary changes, exercise routines, hydration, and sleep hygiene. Take into account existing conditions such as low vitamin D & B12 and current medications like B12 supplements. Ensure recommendations are practical, balanced, and supportive.\\n        \\n    \\n    If necessary, please consider connecting with a healthcare provider for further assistance.\", 'Primary Category': 'Physical Health and Wellness', 'Action': 'Offer guidance, recommend further consultation if needed, and provide empathetic and practical advice.'}\n"
     ]
    }
   ],
   "source": [
    "def determine_category(symptoms):\n",
    "    # Expanded and refined logic to categorize based on symptoms\n",
    "    symptoms_lower = symptoms.lower()\n",
    "    \n",
    "    physical_health_keywords = [\n",
    "        \"headache\", \"pain\", \"fever\", \"runny nose\", \"cough\", \n",
    "        \"fatigue\", \"bloating\", \"constipation\", \"nausea\", \"muscle ache\"\n",
    "    ]\n",
    "    mental_health_keywords = [\n",
    "        \"anxiety\", \"stress\", \"depression\", \"mood\", \"sleep\", \n",
    "        \"panic\", \"overwhelm\", \"burnout\", \"insomnia\"\n",
    "    ]\n",
    "    sexual_health_keywords = [\n",
    "        \"sti\", \"sexual\", \"intimacy\", \"partner\", \"sexual health\", \n",
    "        \"rash\", \"itching\", \"discharge\", \"erectile dysfunction\"\n",
    "    ]\n",
    "    \n",
    "    if any(keyword in symptoms_lower for keyword in physical_health_keywords):\n",
    "        return \"Physical Health and Wellness\"\n",
    "    elif any(keyword in symptoms_lower for keyword in mental_health_keywords):\n",
    "        return \"Mental and Emotional Health\"\n",
    "    elif any(keyword in symptoms_lower for keyword in sexual_health_keywords):\n",
    "        return \"Sexual Health and Intimacy\"\n",
    "    else:\n",
    "        return \"General Wellness\"  # Default category if symptoms don't match specific criteria\n",
    "\n",
    "def generate_optimized_prompt(customer_data):\n",
    "    # Determine the category based on symptoms\n",
    "    category = determine_category(customer_data.get(\"symptoms\", \"\"))\n",
    "    \n",
    "    # Generate category-specific recommendations\n",
    "    category_specific_content = \"\"\n",
    "    if category == \"Physical Health and Wellness\":\n",
    "        category_specific_content = f\"\"\"\n",
    "        Provide a personalized set of recommendations to enhance the user's physical well-being. Address their symptoms: {customer_data.get('symptoms')}. Include suggestions for dietary changes, exercise routines, hydration, and sleep hygiene. Take into account existing conditions such as {customer_data.get('conditions')} and current medications like {customer_data.get('medications')}. Ensure recommendations are practical, balanced, and supportive.\n",
    "        \"\"\"\n",
    "    elif category == \"Mental and Emotional Health\":\n",
    "        category_specific_content = f\"\"\"\n",
    "        Create a supportive and professional response to help the user manage feelings of stress or other emotional challenges. Address their symptoms: {customer_data.get('symptoms')}. Offer techniques such as mindfulness exercises, structured routines, and tips for managing stress and anxiety. Include encouragement to seek further support or counseling if necessary, with an empathetic and compassionate approach.\n",
    "        \"\"\"\n",
    "    elif category == \"Sexual Health and Intimacy\":\n",
    "        category_specific_content = f\"\"\"\n",
    "        Provide a professional and compassionate response to the user's concerns about sexual health or STI-related issues. Address their symptoms: {customer_data.get('symptoms')}. Include guidance on confidential testing, safe practices, and addressing symptoms like {customer_data.get('symptoms')}. Emphasize the importance of medical consultation when needed and maintain a non-judgmental, supportive tone.\n",
    "        \"\"\"\n",
    "\n",
    "    # Generate the response string using customer data and the relevant category content\n",
    "    response = f\"\"\"\n",
    "    Hi {customer_data.get('name')}, I am Waaban, a virtual health assistant designed to provide personalized health and wellness guidance. Based on your provided information, here is my response:\n",
    "    \n",
    "    {category_specific_content}\n",
    "    \n",
    "    If necessary, please consider connecting with a healthcare provider for further assistance.\n",
    "    \"\"\"\n",
    "    \n",
    "    # Return the data in JSON format\n",
    "    output = {\n",
    "        \"Subject\": f\"Health Guidance for {customer_data.get('name')}\",\n",
    "        \"Response\": response.strip(),\n",
    "        \"Primary Category\": category,\n",
    "        \"Action\": \"Offer guidance, recommend further consultation if needed, and provide empathetic and practical advice.\"\n",
    "    }\n",
    "    \n",
    "    return output\n",
    "\n",
    "# Example usage\n",
    "customer_data = {\n",
    "    \"name\": \"Rupin Munjal\",\n",
    "    \"phone\": \"1234567890\",\n",
    "    \"symptoms\": \"I feel nauseous and have a headache, I went to a strip club last night and had sex with a stripper\",\n",
    "    \"age\": \"19\",\n",
    "    \"gender\": \"male\",\n",
    "    \"location\": \"Oakville\",\n",
    "    \"conditions\": \"low vitamin D & B12\",\n",
    "    \"medications\": \"B12 supplements\",\n",
    "    \"allergies\": \"\",\n",
    "    \"vaccination_status\": \"I am fully vaccinated\",\n",
    "    \"medical_history\": \"\",\n",
    "    \"family_history\": \"\",\n",
    "    \"surgery_history\": \"\",\n",
    "    \"pregnancy_status\": \"I am not pregnant\",\n",
    "    \"smoking_status\": \"I am a non-smoker\",\n",
    "    \"alcohol_consumption\": \"\",\n",
    "    \"exercise_frequency\": \"I exercise daily\",\n",
    "    \"sleep_duration\": \"I get 7-8 hours of sleep\",\n",
    "    \"physical_activity\": \"I do physical activity\",\n",
    "    \"diet_preferences\": \"I eat a balanced diet\",\n",
    "}\n",
    "\n",
    "# Generate prompt\n",
    "output = generate_optimized_prompt(customer_data)\n",
    "print(output)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 107,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "**Personalized Response**\n",
      "\n",
      "Dear [Customer],\n",
      "\n",
      "I hope this message finds you well. I'm Waaban, your virtual health assistant, and I'm here to support you in addressing your concerns about the rash on your penis.\n",
      "\n",
      "Firstly, please know that I'm not a substitute for a healthcare professional, and it's essential to consult a doctor for proper diagnosis and treatment. That being said, I'll provide you with some general guidance and recommendations that may support your overall well-being.\n",
      "\n",
      "**Symptom Management:**\n",
      "\n",
      "Maintaining good genital hygiene is essential in managing symptoms. Make sure to:\n",
      "\n",
      "1. Wash the affected area gently with mild soap and lukewarm water.\n",
      "2. Pat dry and avoid direct pressure or friction.\n",
      "3. Wear loose, breathable clothing to reduce irritation.\n",
      "\n",
      "**General Wellness:**\n",
      "\n",
      "1. **Stay hydrated**: Drink plenty of water to help flush out toxins and keep your skin hydrated.\n",
      "2. **Consult a doctor**: Schedule an appointment with your primary care physician or visit a local urgent care center to get a proper diagnosis and treatment plan.\n",
      "3. **Practice good hygiene**: Regularly shower or bathe to maintain personal cleanliness.\n",
      "\n",
      "**Additional Recommendations:**\n",
      "\n",
      "1. **Avoid scratching**: Scratching can lead to further irritation and potentially spread bacteria.\n",
      "2. **Keep the area clean**: Use an antiseptic cream or ointment to reduce bacterial growth.\n",
      "3. **Consider over-the-counter creams or ointments**: If your doctor recommends, you can try over-the-counter creams or ointments to help alleviate symptoms.\n",
      "\n",
      "**Local Healthcare Providers:**\n",
      "\n",
      "To find a local healthcare provider or urgent care center, you can try the following resources:\n",
      "\n",
      "1. **Urgent care near your location**: Use online directories like Visiting Nurse Associations or Your Area Urgent Care to find a nearby urgent care center.\n",
      "2. **Primary care physician**: Reach out to your usual primary care physician or ask for a referral to a specialist, such as a dermatologist.\n",
      "\n",
      "**Actionable Steps:**\n",
      "\n",
      "1. Schedule a follow-up appointment with your primary care physician or visit a local urgent care center.\n",
      "2. Wash the affected area gently and maintain good genital hygiene.\n",
      "3. Stay hydrated and avoid scratching the affected area.\n",
      "\n",
      "**Additional Resources:**\n",
      "\n",
      "For more information on genital health and hygiene, you can visit the following websites:\n",
      "\n",
      "1. **Centers for Disease Control and Prevention (CDC)**: [www.cdc.gov](http://www.cdc.gov)\n",
      "2. **American Urological Association (AUA)**: [www.auanet.org](http://www.auanet.org)\n",
      "\n",
      "Please know that I'm here to support you, but it's essential to consult a healthcare professional for personalized guidance. If you have any further questions or concerns, feel free to reach out to me.\n",
      "\n",
      "Best regards,\n",
      "\n",
      "Waaban\n",
      "Virtual Health Assistant\n"
     ]
    }
   ],
   "source": [
    "raw_response = client.chat.completions.create(\n",
    "    model=\"llama-3.2-3b-preview\",\n",
    "    messages=[{\"role\": \"user\", \"content\": prompt}]\n",
    ")\n",
    "response = raw_response.choices[0].message.content\n",
    "print(response)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
